[deploy]
bucket = 'cfn-artifacts.awsbootcamp.online'
region = 'eu-west-1'
stack_name = 'CrdSyncRole'

[parameters]
GitHubOrg = 'feleck'
RepositoryName = 'aws-bootcamp-cruddur-2023'
OIDCProviderArn = ''