[deploy]
bucket = 'cfn-artifacts.awsbootcamp.online'
region = 'eu-west-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://awsbootcamp.online'
EnvBackendUrl = 'https://api.awsbootcamp.online'
DDBMessageTable = 'CrdDdb-DynamoDBTable-1OISG6TCEOGI9'