#!/usr/bin/env bash

set -e

ABS_PATH=$(readlink -f "$0")
BACKEND_PATH=$(dirname $ABS_PATH)
SAM_PATH=$(dirname $BACKEND_PATH)
BIN_PATH=$(dirname $SAM_PATH)
PROJECT_PATH=$(dirname $BIN_PATH)

FUNC_DIR="$PROJECT_PATH/aws/lambdas/cruddur-messaging-stream/"
CFN_PATH="$PROJECT_PATH/aws/cfn"
CONFIG_PATH="$CFN_PATH/ddb/config.toml"

TEMPLATE_PATH="$PROJECT_PATH/.aws-sam/build/template.yaml"
TEMPLATE_PATH="$PROJECT_PATH/aws/cfn/ddb/template.yaml"

sam validate -t $TEMPLATE_PATH

sam build \
    --config-file $CONFIG_PATH \
    --template $TEMPLATE_PATH \
    --use-container \
    --base-dir $FUNC_DIR
    # --build-dir $FUNC_DIR \
    # --parameter-overrides \

    # use-container is for building the lambda in a container not that we are using a custom - uses runtime