#!/usr/bin/env bash

set -e

ABS_PATH=$(readlink -f "$0")
BACKEND_PATH=$(dirname $ABS_PATH)
SAM_PATH=$(dirname $BACKEND_PATH)
BIN_PATH=$(dirname $SAM_PATH)
PROJECT_PATH=$(dirname $BIN_PATH)

# FUNC_DIR="$PROJECT_PATH/aws/lambdas/cruddur-messaging-stream"
CFN_PATH="$PROJECT_PATH/aws/cfn"
CONFIG_PATH="$CFN_PATH/ddb/config.toml"
PACKAGED_TEMPLATE_PATH="$PROJECT_PATH/.aws-sam/build/packaged.yaml"

sam deploy \
    --template-file $PACKAGED_TEMPLATE_PATH \
    --config-file $CONFIG_PATH \
    --stack-name "CrdDdb" \
    --no-execute-changeset \
    --tags group=cruddur-ddb \
    --capabilities "CAPABILITY_NAMED_IAM"
