#!/usr/bin/env bash

set -e

ABS_PATH=$(readlink -f "$0")
BACKEND_PATH=$(dirname $ABS_PATH)
SAM_PATH=$(dirname $BACKEND_PATH)
BIN_PATH=$(dirname $SAM_PATH)
PROJECT_PATH=$(dirname $BIN_PATH)

# FUNC_DIR="$PROJECT_PATH/aws/lambdas/cruddur-messaging-stream/"
CFN_PATH="$PROJECT_PATH/aws/cfn"
CONFIG_PATH="$CFN_PATH/ddb/config.toml"

ARTIFACT_BUCKET="cfn-artifacts.awsbootcamp.online"
TEMPLATE_PATH="$PROJECT_PATH/.aws-sam/build/template.yaml"
OUTPUT_TEMPLATE_PATH="$PROJECT_PATH/.aws-sam/build/packaged.yaml"

sam package \
    --s3-bucket $ARTIFACT_BUCKET \
    --config-file $CONFIG_PATH \
    --output-template-file $OUTPUT_TEMPLATE_PATH \
    --template-file $TEMPLATE_PATH \
    --s3-prefix "ddb"